export const products = [
	{
		id: 1,
		name: 'Смартфон Samsung Galaxy A54',
		price: 399.99,
		category: 'Электроника',
		inStock: true,
		brand: 'Samsung',
		rating: 4.5,
		reviewsCount: 128,
		description:
			'Современный смартфон с ярким Super AMOLED дисплеем, мощным процессором и отличной камерой.',
		images: ['/images/samsung-a54-1.jpg', '/images/samsung-a54-2.jpg'],
		specifications: {
			display: '6.4 дюйма, Super AMOLED',
			processor: 'Exynos 1380',
			ram: '6 ГБ',
			storage: '128 ГБ',
			battery: '5000 мАч',
			camera: '50 МП + 12 МП + 5 МП',
			os: 'Android 13',
		},
		discount: 10,
		createdAt: '2024-03-20T14:00:00Z',
		updatedAt: '2024-04-01T10:30:00Z',
	},
	{
		id: 2,
		name: 'Ноутбук ASUS VivoBook',
		price: 799.99,
		category: 'Компьютеры',
		inStock: true,
		brand: 'ASUS',
		rating: 4.3,
		reviewsCount: 85,
		description:
			'Надежный и производительный ноутбук для работы и учебы, с экраном Full HD и SSD накопителем.',
		images: ['/images/asus-vivobook-1.jpg', '/images/asus-vivobook-2.jpg'],
		specifications: {
			display: '15.6 дюймов, Full HD',
			processor: 'Intel Core i5 11-го поколения',
			ram: '8 ГБ',
			storage: '512 ГБ SSD',
			battery: '42 Вт·ч',
			os: 'Windows 11',
		},
		discount: 15,
		createdAt: '2024-02-10T09:00:00Z',
		updatedAt: '2024-04-02T12:00:00Z',
	},
	{
		id: 3,
		name: 'Беспроводные наушники JBL Tune 510BT',
		price: 59.99,
		category: 'Аудио',
		inStock: false,
		brand: 'JBL',
		rating: 4.7,
		reviewsCount: 213,
		description:
			'Компактные и удобные беспроводные наушники с чистым звуком и длительным временем работы.',
		images: ['/images/jbl-510bt-1.jpg', '/images/jbl-510bt-2.jpg'],
		specifications: {
			connection: 'Bluetooth 5.0',
			batteryLife: 'до 40 часов',
			chargingTime: '2 часа',
			weight: '160 г',
			color: 'Черный',
		},
		discount: 5,
		createdAt: '2024-01-05T11:00:00Z',
		updatedAt: '2024-03-15T08:20:00Z',
	},
]
